dirs:
    train:
        data: /mnt/lustre/xushuang/easton/data/AISHELL-2/iOS/data/train_1kh_char.csv
        tfdata: /mnt/lustre/xushuang/easton/projects/asr-ctc-tf/exp/aishell/char_data/train
    dev:
        data: /mnt/lustre/xushuang/easton/data/AISHELL-2/iOS/dev/dev_char.csv
        tfdata: /mnt/lustre/xushuang/easton/projects/asr-ctc-tf/exp/aishell/char_data/dev
    test:
        # data: /mnt/lustre/xushuang/easton/data/AISHELL-2/iOS/test/test_char.csv
        data: /mnt/lustre/xushuang/easton/data/AISHELL-2/iOS/dev/dev_char.csv
    type: csv
    models: models
    vocab: /mnt/lustre/xushuang/easton/projects/asr-tf/exp/aishell/vocab_5978+1.txt
    log: log
    checkpoint: checkpoint
    # acoustic_checkpoint: /mnt/lustre/xushuang/easton/projects/asr-tf/exp/aishell/models/ctc_char_cp0.2.yaml/checkpoint/
    # checkpoint_init: /mnt/lustre/xushuang/easton/projects/asr-tf/exp/aishell/models/ctc_char_base.yaml/checkpoint/

data:
    dim_raw_input: 80
    num_context: 0
    downsample: 1
    add_delta: True
    input_noise: 0
    unit: word
    train:
        size_dataset:
    dev:
        size_dataset:

model:
    encoder:
        type: conv_lstm
        num_cell_units: 1600
        num_filters: 64
        use_residual: False
        dropout: 0.0
    decoder:
        type: fc_decoder
        ctc_merge_repeated: True
        confidence_penalty: 0.3
    structure: ctcModel
    prob_start: 0.5
    prob_end: 0.5
    interim_steps: 10000
    start_warmup_steps: 20000

dev_step: 500
decode_step: 50
save_step: 200

# gpus: '1, 2'
gpus: '0,1,2,3'

num_epochs: 100000
keep_training: True
num_steps: 500000

bucket_boundaries: 185,208,228,247,267,284,301,317,332,348,364,381,398,416,434,454,475,498,523,550,582,619,667,741,956,1931
batch_size: 40
num_batch_tokens: 33000

opti:
    beta1: 0.9
    beta2: 0.999
    epsilon: 1e-8

default_stddev: 0.046875

# learning rate
optimizer: adam
warmup_steps: 6000
peak: 0.0002
decay_steps: 8000
beam_size: 1
# beam_size: 10
num_threads: 8

length_penalty_weight: 0.0
lamda_l2: 0.0

grad_clip_value: 0.0
slot_clip_value: 0.0
grad_clip_norm: 0.0
grad_clip_global_norm: 0.0
