dirs:
    train:
        data: /mnt/lustre/xushuang/easton/data/AISHELL-2/iOS/data/train_1kh_char.csv
        tfdata: /mnt/lustre/xushuang/easton/projects/asr-ctc-tf/exp/aishell/char_eos_data/train
    dev:
        data: /mnt/lustre/xushuang/easton/data/AISHELL-2/iOS/dev/dev_char.csv
        tfdata: /mnt/lustre/xushuang/easton/projects/asr-ctc-tf/exp/aishell/char_eos_data/dev
    test:
        data: /mnt/lustre/xushuang/easton/data/AISHELL-2/iOS/test/test_char.csv
        # data: /mnt/lustre/xushuang/easton/data/AISHELL-2/iOS/dev/dev_char.csv
    type: csv
    models: models
    vocab: /mnt/lustre/xushuang/easton/projects/asr-tf/exp/aishell/vocab_5978+2.txt
    log: log
    checkpoint: checkpoint
    checkpoint_init: /mnt/lustre/xushuang/easton/projects/asr-tf/exp/aishell/models/transformer.yaml/checkpoint

    # lm_checkpoint: /mnt/lustre/xushuang/easton/projects/nmt-tf/exp/aishell2/models/aishell2_dev.yaml/checkpoint/
    # lm_config: /mnt/lustre/xushuang/easton/projects/nmt-tf/exp/aishell2/configs/aishell2_dev.yaml
    lm_checkpoint: /mnt/lustre/xushuang/easton/projects/nmt-tf/exp/aishell2/models/aishell2.yaml/checkpoint/
    lm_config: /mnt/lustre/xushuang/easton/projects/nmt-tf/exp/aishell2/configs/aishell2.yaml
    # lm_checkpoint: /mnt/lustre/xushuang/easton/projects/nmt-tf/exp/aishell2/models/aishell2_bigtrain.yaml/checkpoint/
    # lm_config: /mnt/lustre/xushuang/easton/projects/nmt-tf/exp/aishell2/configs/aishell2_bigtrain.yaml

data:
    dim_raw_input: 80
    num_context: 5
    downsample: 3
    add_delta: False
    input_noise: 0
    unit: word
    train:
        size_dataset:
    dev:
        size_dataset:

model:
    encoder:
        type: transformer_encoder
        num_blocks: 6
        num_heads: 8
        num_cell_units: 512
        attention_dropout_rate: 0.1
        residual_dropout_rate: 0.1
    decoder:
        type: transformer_decoder
        size_embedding: 512
        num_blocks: 6
        num_heads: 8
        num_cell_units: 512
        attention_dropout_rate: 0.1
        residual_dropout_rate: 0.1
        init_scale: 0.04
        label_smoothing_confidence: 0.9
    structure: transformer
    loss_type: CE
    prob_start: 0.1
    prob_end: 3.0
    start_warmup_steps: 8000
    interim_steps: 10000
    shallow_fusion: True
    rerank: True

dev_step: 500
decode_step: 50
save_step: 500

# gpus: '1'
gpus: '0,1,2,3'

num_epochs: 100000
keep_training: True
num_steps: 500000

bucket_boundaries: 61,69,76,82,89,94,100,105,110,116,121,127,132,138,144,151,158,166,174,183,194,206,222,247,318,643
num_batch_tokens: 18000

opti:
    beta1: 0.9
    beta2: 0.999
    epsilon: 1e-8

default_stddev: 0.046875

# learning rate
optimizer: adam
warmup_steps: 15000
peak: 0.0002
decay_steps: 15000
# beam_size: 1
beam_size: 50
num_threads: 8

length_penalty_weight: 0.0
lamda_l2: 0.0
lambda_lm: 0.2
lambda_rerank: 0.0

grad_clip_value: 0.0
slot_clip_value: 0.0
grad_clip_norm: 0.0
grad_clip_global_norm: 0.0
