dirs:
    train:
        # data: /mnt/lustre/xushuang/easton/data/hkust/word/train_dev/feats.train_dev.scp
        # label: /mnt/lustre/xushuang/easton/data/hkust/word/train_dev/word.train_dev.scp
        # tfdata: /mnt/lustre/xushuang/easton/data/hkust/word_eos/train_dev
        data: /mnt/lustre/xushuang/easton/data/hkust/word/train/feats.train_3x.scp
        label: /mnt/lustre/xushuang/easton/data/hkust/word/train/word.train_3x.scp
        tfdata: /mnt/lustre/xushuang/easton/data/hkust/word_eos/train
    dev:
        data: /mnt/lustre/xushuang/easton/data/hkust/word/train_dev/feats.train_dev.scp
        label: /mnt/lustre/xushuang/easton/data/hkust/word/train_dev/word.train_dev.scp
        tfdata: /mnt/lustre/xushuang/easton/data/hkust/word_eos/train_dev
    test:
        data: /mnt/lustre/xushuang/easton/data/hkust/word/dev/feats.dev.scp
        label: /mnt/lustre/xushuang/easton/data/hkust/word/dev/word.dev.scp
        tfdata: /mnt/lustre/xushuang/easton/data/hkust/word_eos/dev
    type: scp
    models: models
    vocab: /mnt/lustre/xushuang/easton/data/hkust/word_eos/vocab_3673+2.txt
    log: log
    checkpoint: checkpoint
    # checkpoint_init: /mnt/lustre/xushuang/easton/projects/asr-tf/exp/hkust/models/transformer.yaml/checkpoint

data:
    dim_raw_input: 80
    num_context: 5
    downsample: 3
    add_delta: False
    input_noise: 0
    unit: word
    train:
        size_dataset:
    dev:
        size_dataset:

model:
    encoder:
        type: transformer_encoder
        # type: conv_lstm
        # num_cell_units: 1600
        # num_filters: 64
        # use_residual: False
        dropout: 0.0
    decoder:
        type: transformer_decoder
        size_embedding: 512
        num_blocks: 6
        num_heads: 8
        num_cell_units: 512
        attention_dropout_rate: 0.1
        residual_dropout_rate: 0.1
        init_scale: 0.04
        label_smoothing_confidence: 1.0
    structure: transformer
    loss_type: CE
    prob_start: 0.1
    prob_end: 3.0
    start_warmup_steps: 8000
    interim_steps: 10000

dev_step: 5000
decode_step: 1000
save_step: 500

gpus: '0,1,2,3'
# gpus: '0'

num_epochs: 100000
keep_training: True
num_steps: 500000

bucket_boundaries: 122,159,186,208,228,247,264,279,295,310,325,340,354,368,383,399,415,433,450,469,491,514,541,571,609,656,720,822,1010
num_batch_tokens: 20000

opti:
    beta1: 0.9
    beta2: 0.999
    epsilon: 1e-8

default_stddev: 0.046875

# learning rate
optimizer: adam
warmup_steps: 10000
peak: 0.00005
decay_steps: 20000
beam_size: 1
# beam_size: 10
num_threads: 8

length_penalty_weight: 0.0
lambda_l2: 0.0
lambda_lm: 0.0
lambda_rerank: 0.0

grad_clip_value: 0.0
slot_clip_value: 0.0
grad_clip_norm: 0.0
grad_clip_global_norm: 0.0
