agent:
    UCB_param: False
    epsilon: 0.1
    gradient: False
env:
    true_rewards: 1,1,2,3,3,4,5,5,7,7
    true_rewards: 0,1,2,3,4,5,6,7,8,9

times: 50
gradient_baseline: False
learning_rate: 1.0
